server:
  compression:
     enabled: true
     mime-types: application/json,application/xml,text/html,text/xml,text/plain
  server-header: concur-connector
  port: 9500

connector:
  hasTestAuth: true

management:
  endpoints:
    web.base-path: /

# Inorder to fetch the OAuth token, the below properties are required to be configured by the tenant.
concur:
  client-id: 243cc4ce-92e1-4581-a650-a08e04b3ef28
  client-secret: ae5e9172-bbe0-4c82-9400-bb6d227d4f1e
  oauth-instance-url: https://us-impl.api.concursolutions.com/

security:
  oauth2:
    resource:
      jwt:
        key-uri: https://herocard.vmwareidentity.com/SAAS/API/1.0/REST/auth/token?attribute=publicKey&format=pem
